### PR TITLE
Add HentAI

### PR DESCRIPTION
**Pull request by ThatLukinhasGuy**

### CODE REVIEW

**Comment by void6670** [comment]
i agree, you should add this

**Comment by Launchers-1** [comment]
I second this, aswell.

**Review by fuegovic — APPROVED** [review]

**Comment by Launchers-1** [comment]
@fuegovic is the real goat for adding the hentai patch

**Comment by fuegovic** [comment]
Thanks for the contribution

**Comment by fuegovic** [comment]
Forgot to restart the demo to apply the changes, they are live now!
https://demo.librechat.cfd/

**Pull request merged**
